module.exports = {
  INBOX_FETCH:                'inbox:fetch',
  SERVICE_START:              'service:start',
  SERVICE_STOP:               'service:stop',
  SERVICE_STOP_COMPLETED:     'service:stop:completed',
  INBOX_FETCH_COMPLETED:      'inbox:fetch:completed',
  INBOX_FETCH_FAILED:         'inbox:fetch:failed',
  INBOX_EMPTY:                'inbox:empty',
  RESPONSE_PROCESS_COMPLETED: 'response:process:completed',
  RESPONSE_PROCESS_FAILED:    'response:process:failed',
  MESSAGE_PROCESS_COMPLETED:  'message:process:completed',
  MESSAGE_PROCESS_FAILED:     'message:process:failed',
  SERVICE_PROCESS_START:      'service:process:start',
  SERVICE_PROCESS_COMPLETED:  'service:process:completed',
  SERVICE_PROCESS_FAILED:     'service:process:failed',
};
